backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: org-cyf-guides/static/cms
public_folder: /cms

collections:
  - name: "dayPlans"
    label: "Day Plans"
    files:
      - label: "Sprint 1 Day Plan"
        name: "sprint1DayPlan"
        file: "content/sprint/1/day-plan/index.md"
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "day-plan",
            }
          - { label: "Emoji", name: "emoji", widget: "string" }
          - {
              label: "Menu Level",
              name: "menu_level",
              widget: "hidden",
              default: ["sprint"],
            }
          - { label: "Weight", name: "weight", widget: "number" }
          - {
              label: "No Register",
              name: "noRegister",
              widget: "boolean",
              default: false,
            }
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Source", name: "src", widget: "string" }
              - {
                  label: "Time",
                  name: "time",
                  widget: "number",
                  required: false,
                }
              - {
                  label: "Caption",
                  name: "caption",
                  widget: "string",
                  required: false,
                }
      - label: "Sprint 2 Day Plan"
        name: "sprint2DayPlan"
        file: "content/sprint/2/day-plan/index.md"
        create: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "day-plan",
            }
          - { label: "Emoji", name: "emoji", widget: "string" }
          - {
              label: "Menu Level",
              name: "menu_level",
              widget: "hidden",
              default: ["sprint"],
            }
          - { label: "Weight", name: "weight", widget: "number" }
          - {
              label: "No Register",
              name: "noRegister",
              widget: "boolean",
              default: false,
            }
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Source", name: "src", widget: "string" }
              - {
                  label: "Time",
                  name: "time",
                  widget: "number",
                  required: false,
                }
              - {
                  label: "Caption",
                  name: "caption",
                  widget: "string",
                  required: false,
                }
